# controller:
#   installPlugins:
#     - kubernetes:1.29.1
#     - workflow-aggregator:2.6
#     - docker-workflow:1.26
#     # Add other plugins you need

# Master:
#   containers:
#     - name: jenkins
#       image: jenkins/jenkins:lts
#       volumeMounts:
#         - name: jenkins-home
#           mountPath: /var/jenkins_home
#     - name: docker
#       image: docker:latest
#       volumeMounts:
#         - mountPath: /var/run/docker.sock
#           name: docker-socket
#   volumes:
#     - name: jenkins-home
#       emptyDir: {}

# Agent:
#   containers:
#     - name: jnlp
#       args: ["${computer.jnlpmac}"]
#       resources:
#         requests:
#           memory: "256Mi"
#           cpu: "100m"
#         limits:
#           memory: "512Mi"
#           cpu: "200m"
#       volumeMounts:
#         - mountPath: /var/run/docker.sock
#           name: docker-socket
#   volumes:
#     - name: docker-socket
#       hostPath:
#         path: /var/run/docker.sock
