FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]



# # Use the official Python base image
# FROM python:3.9-slim-buster
# # FROM python:3.9

# # Set the working directory inside the container
# WORKDIR /app

# # Copy the current directory contents into the container at /app
# COPY . /app

# # Install app dependencies
# RUN pip install --no-cache-dir Flask

# # Expose the port your Flask app will run on
# EXPOSE 5000

# # Define the command to run your Flask app when the container starts
# CMD ["python", "app.py"]
